version: '3.1'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: dpg-crm54jtumphs73ehth30-a.oregon-postgres.render.com
      DB_USER: itra_04_user
      DB_PASSWORD: QvpkoJGwcp3nr6IBJSJyI24yuFf4ZA7R
      DB_NAME: itra_04
      DB_PORT: 5432
