version: "3.1"

services:
  mysql:
    image: mysql:8.0
    container_name: user-management-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: QlLWWBePfzOJnsCxlKupcfcolrKIOvCi
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: QlLWWBePfzOJnsCxlKupcfcolrKIOvCi
      DB_NAME: railway
      DB_PORT: 3306
