services:
  - type: web
    name: my-node-service
    env: docker
    plan: free
    dockerfile_path: ./Dockerfile
    build_command: ""
    start_command: "node server.js"
    port: 5000
    env_vars:
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        value: "123456789"
      - key: DB_HOST
        value: "dpg-crm54jtumphs73ehth30-a.oregon-postgres.render.com"
      - key: DB_USER
        value: "itra_04_user"
      - key: DB_PASSWORD
        value: "QvpkoJGwcp3nr6IBJSJyI24yuFf4ZA7R"
      - key: DB_NAME
        value: "itra_04"
      - key: DB_PORT
        value: "5432"
  - type: db
    name: my-postgres-db
    env: postgres
    plan: free
    postgres_version: "14"
    env_vars:
      - key: POSTGRES_USER
        value: "itra_04_user"
      - key: POSTGRES_PASSWORD
        value: "QvpkoJGwcp3nr6IBJSJyI24yuFf4ZA7R"
      - key: POSTGRES_DB
        value: "itra_04"
